# Setup
title:               ENDOW
tagline:             'Economic Network Dynamics & the Origins of Wealth Inequality'
description:         'The ENDOW Project'
url:                 https://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 

# Theme
remote_theme: poole/lanyon
